### ISSUE TITLE
Request: Please upload a sample script for getting fault information

### ISSUE THREAD

**Issue by bingoarun** [CiscoUcs/ucsmsdk_samples#23]
Please create a sample script for getting fault information using ucsmsdk as similar to this one https://github.com/CiscoUcs/UcsPythonSDK/blob/master/samples/getFaults.py 

Things I tried earlier -

1) Following this http://blog.vijayvikrant.com/python-ucsmsdk-metadata-and-mo-information-2/ , 

I searched the class ID using search_class_id for "FaultInst". It prints the class_id "FaultInst"
then 
mo = load_class("FaultInst")
write_object(mo)
But it prints "None"

2) 

mo = load_mo("FaultInst")
write_object(mo)

But here it results "AttributeError: 'unicode' object has no attribute 'tag'"

**Comment by waghswapnil** [comment]
@bingoarunprasath: Following is a very basic sample script for getting faults using the latest ucsmsdk

```
from ucsmsdk.ucshandle import UcsHandle

handle = UcsHandle(ip, username, password)
handle.login()

mo_list = handle.query_classid("FaultInst")
for mo in mo_list:
    print(mo.code, mo.severity, mo.descr)
```

Regarding the usage of load_mo and load_class, these create an instance of object of that type and do not get it by querying the ucs system.
Thanks for catching the issue with load_mo.
load_mo expects an `xmlElement` as an input and not class_id. The docstring needs correction along with a minor fix in the code.

I believe, it is expected to work like the following:-

```
from ucsmsdk.ucscoreutils import load_mo
import xml.etree.ElementTree as ET
f = ET.Element('FaultInst')
f.set('code', 'generic')
mo = load_mo(f)
print mo

Managed Object             :          FaultInst
--------------
ack                             :None
cause                           :None
change_set                      :None
child_action                    :None
code                            :generic
created                         :None
descr                           :None
dn                              :fault-generic
highest_severity                :None
id                              :None
last_transition                 :None
lc                              :None
occur                           :None
orig_severity                   :None
prev_severity                   :None
rn                              :fault-generic
rule                            :None
sacl                            :None
severity                        :None
status                          :None
tags                            :None
type                            :None

```

**Comment by bingoarun** [comment]
@waghswapnil : Thank you, That works !!
